services:
  tms:
  demo:
  wmts:
  wms:
    md: 
      title: MapProxy
sources:      
  gm:
    type: tile
    url: http://mt1.google.com/vt/lyrs=s&x=%(x)s&y=%(y)s&z=%(z)s
    grid: epsg_3857
  osm:
    type: tile
    url: http://a.tile.openstreetmap.org/%(z)s/%(x)s/%(y)s.png
    grid: epsg_3857
  youtube:
    type: wms
    http:
      ssl_no_cert_checks: True
    req:
      url: http://localhost:8080/geoserver/yt/wms?
      layers: youtube
      transparent: true
grids:
  epsg_900913:
    base: GLOBAL_MERCATOR
    origin: ul  
  global_mercator:
    base: GLOBAL_WEBMERCATOR
    origin: ul 
  epsg_4326:
    base: GLOBAL_GEODETIC
    
caches:
  gm_cache:
    grids: [global_mercator]
    sources: [gm]
    cache:
      type: file
      directory_layout: tms
  osm_cache:
    grids: [global_mercator]
    sources: [osm]
    cache:
      type: file
      directory_layout: tms
  yt_cache:
    grids: [global_mercator]
    sources: [youtube]
    cache:
      type: file
      directory_layout: tms
      
layers:
  - name: google
    title: google
    sources: [gm_cache]
  - name: osm
    title: OSM
    sources: [osm_cache]  
  - name: youtube
    title: ALTLIK HARITA
    sources: [yt_cache]
